apiVersion: v1
description: "Deployment wrapper for traefik"
name: "traefik-app"
version: 32.1.1

dependencies:
  - name: "loki-distributed"
    alias: "loki"
    condition: "loki.enabled"
    version: "0.79.4"
    repository: "https://grafana.github.io/helm-charts"
  - name: "promtail"
    condition: "promtail.enabled"
    version: "6.16.6"
    repository: "https://grafana.github.io/helm-charts"
  - name: "kube-prometheus-stack"
    alias: "prometheus"
    condition: "prometheus.enabled"
    version: "66.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"