apiVersion: v1
description: "Deployment wrapper for traefik"
name: "monitoring-app"
version: 1.0.0

dependencies:
  - name: "kube-prometheus-stack"
    alias: "prometheus"
    condition: "prometheus.enabled"
    version: "66.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"