apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/treboulit/kubernetes-environment-concept.git"
  password: "ghp_"  # + "A9UmNFEg9e37LyC5bpGS5wrZnkiASG1dOQ6v"
  username: ""