apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/treboulit/kubernetes-environment-concept.git"
  password: "ghp_"  # + "YcukYDwxbW6Ja4i58hXGnobh26bh670GvcE2"
  username: ""