apiVersion: v1
description: "Deployment spring-boot-app example"
name: "spring-sample-app"
version: 1.0.0

dependencies:
  - name: "quarkus-app"
    version: "1.0.0"
    repository: "https://helm.ligidi.africa"