apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ligidi-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/whoami-ligidi/`)
      kind: Rule
      services:
        - name: whoami
          port: http
  tls: {}
