apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-repository
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/argocd/helm-repository/helm.localhost/{{ .Values.localhost.ip }}
    repoURL: https://github.com/jwausle/gitops.argocd.treboul.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
