apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(\`/whoami/\`)
      kind: Rule
      services:
        - name: whoami
          port: http
  tls: {}
