apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
#  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.6/manifests/install.yaml
  - applications.argoproj.io.yaml
  - applicationsets.argoproj.io.yaml
  - appprojects.argoproj.io.yaml
