apiVersion: v2
name: spring-boot-app
description: A Helm chart for running any kind of spring boot applications

appVersion: "1.0"

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.1

