apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-app.fullname" . }}-config
  labels:
    {{- include "quarkus-app.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- include "quarkus-app.mergedConfig" . | nindent 4 }}
    {{- $secrets := (include "quarkus-app.secrets" . | fromYaml).secrets }}
    {{- if $secrets }}
    ---
    # (Magic) Import mounted kubernetes secrets as application properties
    smallrye:
      config:
        source:
          file:
            locations: /var/run/secrets/app/
    {{- end }}