apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-app.fullname" . }}
  labels:
  # Use `with` instead `toYaml .Values.service.labels`, because toYaml would otherwise render "{}" instead of an empty string
    {{- with .Values.service.labels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end}}
    {{- include "quarkus-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "quarkus-app.applicationPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "quarkus-app.selectorLabels" . | nindent 4 }}
