argocd:
  namespace: argocd

cert-manager:
  # 'enabled: true' installation of cert-manager
  #  - it's required for the 'tls.letsEncrypt.enabled: true' option to work
  enabled: true
  installCRDs: true

traefik:
  ingressClass:
    enabled: true
    isDefaultClass: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
      allowExternalNameServices: true
  ports:
    websecure:
      tls:
        enabled: true
    web:
      redirectTo:
        port: websecure
  
  service:
    ipFamilyPolicy: "PreferDualStack"

  # Create an IngressRoute for the dashboard
  ingressRoute:
    dashboard:
      enabled: true
      # Custom match rule with host domain
      matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      entryPoints: [ "websecure" ]
      # Add custom middlewares : authentication and redirection
      middlewares:
        - name: traefik-dashboard-auth

  # Create the custom middlewares used by the IngressRoute dashboard (can also be created in another way).
  extraObjects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: traefik-dashboard-auth-secret
      type: kubernetes.io/basic-auth
      stringData:
        username: admin
        password: admin

    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: traefik-dashboard-auth
      spec:
        basicAuth:
          secret: traefik-dashboard-auth-secret

tls:
  # Enables the creation of a Traefik TLSStore that uses the specified secret
  # as its default certificate. As a result, all routes should be secured.
  enabled: true
  # The name of the secret that holds the TLS cert and key in PEM format. If
  # letsEncrypt is disabled but tls is enabled you should make sure that the
  # secret exists prior to installing this helmchart release
  secretName: tls-store
  letsEncrypt:
    # Enables the creation of a cluster issuer and certificate request to obtain
    # an officiallz signed certificate from Let's Encrypt. Requires that
    # cert-manager is enabled or installed as well.
    enabled: false
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: winter@jwausle.de
    domains:
      - ligidi.africa
      - argocd.ligidi.africa
      - docker.ligidi.africa
      - helm.ligidi.africa
