quarkus:
  http:
    port: 8081

sample:
  config:
    key: "sample-config"
    value: "config"
  secret:
    key: "sample-secret"
    value: "secret"
  html-background-color: "lightgray"

my-secret: "must-overwrite"
my-secret2: "must-overwrite yaml"

# Reset ordinal:255 to 99 to support overwriting by FileSystem Config Source
# - ordinal doc: https://smallrye.io/smallrye-config/3.10.2/config/getting-started/
# - file system: https://smallrye.io/smallrye-config/3.10.2/config-sources/filesystem/
config_ordinal: 99
