apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.prometheus.grafana.admin.existingSecret }}"
  namespace: "{{ .Values.app.namespace }}"
stringData:
  admin-password: "{{ .Values.app.grafana.admin.password }}"
  admin-user: "{{ .Values.app.grafana.admin.username }}"