apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "prometheus-grafana"
  namespace: "{{ .Values.app.namespace }}"
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`{{ .Values.prometheus.grafana.ingress.path }}`)
      kind: Rule
      services:
        - name: prometheus-grafana
          port: 80
  tls: {}