apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: prometheus-grafana
          port: 80
  tls: {}