apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prometheus-pv-claim"
  namespace: "monitoring"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"