# Enabled by default
chunksCache:
  persistence:
    # Persistence is disabled by default
    enabled: true
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: "local-path"

deploymentMode: SingleBinary

loki:
  containerSecurityContext:
    # Solved https://github.com/grafana/helm-charts/issues/1111
    # - grafana-error: /var/loki/chunks/fake/755005aa5e414340/MTgxMTNjOGM5MGI6MTgxMTQzNmE2NTI6M2RkYjQzYmQ=: no such file or directory
    # - found fix: https://community.grafana.com/t/query-error-loki-reporting-to-grafana-it-cant-find-chunks/61741/2
    readOnlyRootFilesystem: false

singleBinary:
  persistence:
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: "local-path"