apiVersion: v1
kind: LimitRange
metadata:
  name: ligidi-limit-range
  namespace: ligidi
spec:
  limits:
    - default:
        memory: 1Gi
      defaultRequest:
        memory: 512Mi
      type: Container