name: Build Service

on:
  push:
    branches:
      - main
    paths:
      - 'service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'service/pom.xml'
      - name: Build
        run: mvn -B clean package --file service/pom.xml
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: ./service/target/
