name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'service/**'  # Trigger only if changes happen in this subdirectory
  pull_request:
    branches:
      - main
    paths:
      - 'service/**'  # Trigger only if changes happen in this subdirectory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java sources in subdirectory
        run: |
          mvn clean package
        working-directory: ./service
